# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-08 07:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assets_type', models.CharField(choices=[('server', '\u670d\u52a1\u5668'), ('switch', '\u4ea4\u6362\u673a')], default='server', max_length=100, verbose_name='\u8d44\u4ea7\u7c7b\u578b')),
                ('management_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='\u7ba1\u7406IP')),
            ],
            options={
                'db_table': 'opsmanage_assets',
                'verbose_name': '\u603b\u8d44\u4ea7\u8868',
                'verbose_name_plural': '\u603b\u8d44\u4ea7\u8868',
                'permissions': (('can_read_assets', '\u8bfb\u53d6\u8d44\u4ea7\u6743\u9650'), ('can_change_assets', '\u66f4\u6539\u8d44\u4ea7\u6743\u9650'), ('can_add_assets', '\u6dfb\u52a0\u8d44\u4ea7\u6743\u9650'), ('can_delete_assets', '\u5220\u9664\u8d44\u4ea7\u6743\u9650')),
            },
        ),
        migrations.CreateModel(
            name='Server_Assets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('hostname', models.CharField(blank=True, max_length=100, null=True)),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('passwd', models.CharField(blank=True, max_length=100, null=True)),
                ('keyfile', models.SmallIntegerField(blank=True, null=True)),
                ('port', models.DecimalField(blank=True, decimal_places=0, max_digits=6, null=True)),
                ('cpu', models.CharField(blank=True, max_length=100, null=True)),
                ('assets', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='appone.Assets')),
            ],
            options={
                'db_table': 'opsmanage_server_assets',
                'verbose_name': '\u670d\u52a1\u5668\u8d44\u4ea7\u8868',
                'verbose_name_plural': '\u670d\u52a1\u5668\u8d44\u4ea7\u8868',
                'permissions': (('can_read_server_assets', '\u8bfb\u53d6\u670d\u52a1\u5668\u8d44\u4ea7\u6743\u9650'), ('can_change_server_assets', '\u66f4\u6539\u670d\u52a1\u5668\u8d44\u4ea7\u6743\u9650'), ('can_add_server_assets', '\u6dfb\u52a0\u670d\u52a1\u5668\u8d44\u4ea7\u6743\u9650'), ('can_delete_server_assets', '\u5220\u9664\u670d\u52a1\u5668\u8d44\u4ea7\u6743\u9650')),
            },
        ),
    ]
